os: Visual Studio 2019
version: "{build}"
build: off
platform: x86
environment:
  GITHUB_TOKEN:
    secure: 7DbjX4uP2yRGXrAatRmIByOfDfeio/WWMTGI9RfHqztpvsj6lI37TaTXGunQkjB+
  matrix:
  - nodejs_version: "14"
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install --build-from-source
on_success:
  - if [%prebuild%] == [true] npm run upload:win